application:
  port: 8000
#  host: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5435
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: true
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "E662D7B5D5A0B30F0A10AD0B3B06FDA36C1EBC2C52E238E4EE54F90C85CDA3539A9551B6B563495E554BF3119C5D7A06"
  timeout_milliseconds: 10000
